# Generated by Django 2.1 on 2018-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180820_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='emailAddress',
            new_name='email',
        ),
    ]
